language: r

r:
    - oldrel
    - release
    - devel
      
notifications:
 email:
  recipients:
   - pk.roger@icloud.com
                           
addons:
    apt:
        packages:
            - python-virtualenv

branches:
  only:
    - master
    - /^release[/].*$/
    - /^testing[/]travis-.*$/
   
install:
    - R -e "install.packages(c('getopt', 'devtools'), dependencies = TRUE, repos = 'https://cloud.r-project.org/')"
    - bash install_biodb.sh
    
script: make test && make planemolint && make planemotest
