language: r

r:
    - release

notifications:
 email:
  recipients:
   - pk.roger@icloud.com

env:
    - TEST=test
    - TEST=planemolint
    - TEST=planemotest

addons:
    apt:
        packages:
            - python-virtualenv

branches:
  only:
    - master
    - /^release[/].*$/
    - /^testing[/]travis-.*$/
   
install:
    - python --version
    - make ${TEST}.travis.install
    
script: make $TEST
