language: r

r:
    - release

r_packages: getopt

r_github_packages: pkrog/biodb
      
notifications:
 email:
  recipients:
   - pk.roger@icloud.com
                           
apt_packages: python-virtualenv

branches:
  only:
    - master
    - /^release[/].*$/
    - /^testing[/]travis-.*$/
   
install: echo NOTHING_TO_INSTALL
    
script:
 - make test && make planemolint && make planemotest
