language: r

r: release

notifications:
 email:
  recipients:
   - pk.roger@icloud.com

env:
    - TEST=test
    - TEST=planemolint
    - TEST=planemotest

addons:
    apt:
        packages:
            - python-virtualenv

              #branches:
              #  only:
              #    - master
              #    - /^release[/].*$/
              #    - /^testing[/]travis-.*$/
   
install:
    - [ $TEST = test ] && R -e "install.packages(c('getopt', 'devtools'), dependencies = TRUE, repos = 'https://cloud.r-project.org/')"
    - [ $TEST = test ] && bash install_biodb.sh
    
script: make $TEST
