# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	# Box
	config.vm.box = "ubuntu/trusty64"

	# Set virtual memory. Needed by g++ compiler for compiling R packages (Rcpp).
	config.vm.provider "virtualbox" do |vb|
	    vb.memory = "1024"
	    vb.gui = false
	end

	# Install
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "ansible/lcmsmatching.yml"	
		ansible.sudo = true
	end
end
