# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

	# Box
	config.vm.box = "ubuntu/trusty64"

	# Install
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "ansible/lcmsmatching.yml"	
		ansible.sudo = true
	end
end
